services:
  postgres_db:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: cudev
      POSTGRES_USER: cudev
      POSTGRES_PASSWORD: kotymeow161
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cudev -d cudev"]
      interval: 5s
      timeout: 2s
      retries: 20

  server:
    build:
      context: ./cudev-backend
      dockerfile: Dockerfile
      args:
        - DATABASE_URL=postgresql://cudev:kotymeow161@postgres_db:5432/cudev?schema=public
    ports:
      - "3001:3001"
    depends_on:
      postgres_db:
        condition: service_healthy
    env_file:
      - ./cudev-backend/.env.prod

  frontend:
    build:
      context: ./cudev-frontend
      dockerfile: Dockerfile
    ports:
      - "3002:3000"
    environment:
      - BACKEND_URL=http://server:3001
      - NEXT_PUBLIC_BACKEND_URL=http://186.246.14.241:3001
    depends_on:
      - server

volumes:
  postgres_data: